---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: admin-dashboard-system
spec:
  owner: admins

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: admin-dashboard
spec:
  type: website
  lifecycle: experimental
  owner: admins
  system: admin-dashboard-system